arb-dir: assets/l10n
template-arb-file: app_en.arb
output-localization-file: app_locatization.dart
output-dir: lib/core/l10n
synthetic-package: false
output-class: AppLocalizations
untranslated-messages-file: untranslated.txt

# Enable translation (via DeepL)
translate: true

# Auto-run flutter gen-l10n after extraction
generate: true

# Key prefix for translations
key-prefix: context.l10n.

# Generate key name
# "ask" = Prompt with a suggested key name, true = infer from text, false = prompt manually
auto-name-key: true

# Language to use for key name generation
key-name-language: en

# Import line to insert if needed
import-line: "import 'package:propease/core/utils/extensions.dart';"

target_lang: "EN"
